/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:f034f4b5-7e30-4837-85d6-9b8e9d86a2a8",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_6sklg1Pg8",
    "aws_user_pools_web_client_id": "36itenb03rggb1pj31djmbvs9b",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://n7ejqwrkjbbh3nhrydp7gf534a.appsync-api.ap-southeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-hqy5bez4vzbg5a4des5ap65it4"
};


export default awsmobile;
